### ISSUE TITLE
Unable to find gcloud cli only when using terraform external

### ISSUE THREAD

**Issue by antspy** [terraform-google-modules/terraform-google-kubernetes-engine#2240]
### TL;DR

I am trying to use the `gcloud` cli in a terraform `external` data source (running a script). This works fine locally. 
On github actions, the script also works fine. It only breaks when ran through terraform. 

### Expected behavior

I would like to run the script as normal. 

### Observed behavior

I want to run a `gcloud` command in a terraform script, specifically using `external data`. 
This works fine locally, and `terraform apply` succeeds on my machine. I now want to run this command on github actions. 

I install and authenticate to gcloud on the github actions successfully - in fact, I can run the script: 

```yaml
      - uses: "google-github-actions/auth@v2"
        id: auth
        with:
          ....
          token_format: access_token

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: temp
        run: src/myscript.sh arg0 arg1
```

This works correctly and is able to connect to gcloud, authenticate, and return the expected results.

Now, I want to do the same as an 'external data source' in terraform: 

```hcl
data "external" "my_external_data" {
  program = [
    "${var.repo_root}/src/myscript.sh",
    arg0, arg1
  ]
}
```

When I run terraform apply, the external data script fails because ' gcloud: command not found'

This is very weird, because: 
1. The script runs locally on my machine when called directly. `terraform apply` also works correctly on my machine.
2. The script runs fine when run as a step in the github actions file 
3. It only fails when github actions runs `terraform apply`. 

Note that if I change the script to just `echo "hello"`, then it works (i.e. `hello` is returned). So terraform can find the script, it just does not run it correctly (i.e. it cannot find `gcloud` nor its credentials)

I am assuming this is due to the fact that the external data source is run with some weird environment setup, but I don't understand how to fix it. 
Could someone help? 

Thank you! 

### Terraform Configuration

```hcl
data "external" "my_external_data" {
  program = [
    "${var.repo_root}/src/myscript.sh",
    arg0, arg1
  ]
}
```

### Terraform Version

```sh
Terraform v1.10.3 on linux_amd64
```
