### ISSUE TITLE
Support for configuring Hyperdisk provisioned Throughput and IOPS

### ISSUE THREAD

**Issue by FearlessHyena** [terraform-google-modules/terraform-google-kubernetes-engine#2327]
### TL;DR

Since Hyperdisks allow you to specify the Throughput and IOPS that should be provisioned when creating them, it would be great if the `node_pools` property added support for them 

### Terraform Resources

```markdown

```

### Detailed design

```markdown
Two new variables under the `node_pools` property would be needed which would only be used in case of Hyperdisks and ignored for Persistent disks. The [google_compute_disk resource] (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_disk) can be used for reference
- disk_provisioned_iops
- disk_provisioned_throughput

There is also the [enable_confidential_compute](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_disk#enable_confidential_compute-1) property but not sure if it would be in scope of this feature request
```

**Comment by DrFaust92** [comment]
I think GKE support for this works via https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/2326 storage pools

**Comment by DrFaust92** [comment]
https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/hyperdisk#create according to docs its not directly related to the GKE config and needs to be done by creating a relevant storage class and setting it on relevant PVC:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: balanced-storage
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: hyperdisk-balanced
  provisioned-throughput-on-create: "250Mi"
  provisioned-iops-on-create: "7000"
```

and 

```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: podpvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: balanced-storage
  resources:
    requests:
      storage: 20Gi
```

and using that for your workloads
the above may differ based on your config.

as this is not a module issue I think it cant be closed
