### ISSUE TITLE
GKE compute classes and update-variant

### ISSUE THREAD

**Issue by voron** [terraform-google-modules/terraform-google-kubernetes-engine#2358]
I've faced an unexpected issue while working on  [custom compute classes](https://cloud.google.com/kubernetes-engine/docs/concepts/about-custom-compute-classes#target-specific-node-pools) with manual GKE node pools. Custom compute class requires us to specify nodepool names, f.e
```yaml
      ---
      apiVersion: cloud.google.com/v1
      kind: ComputeClass
      metadata:
        name: rpc-spot
      spec:
        priorities:
          - nodepools: [rpc-1-spot]
          - nodepools: [rpc-0-spot]

```
"Private cluster update variant" version of this module uses dynamic names of node pools to provide "create-before-destroy" option, leading to node pool names like `rpc-0-spot-54a8` and `rpc-1-spot-ab16`.

Are any nice options to use compute classes together with update-variant ?
