### ISSUE TITLE
Switching sync_repo in ACM module does not update on GKE

### ISSUE THREAD

**Issue by ameer00** [terraform-google-modules/terraform-google-kubernetes-engine#650]
Here is my code:
```
module "gke1_acm" {
  source           = "github.com/terraform-google-modules/terraform-google-kubernetes-engine//modules/acm"
  project_id       = data.terraform_remote_state.vpc.outputs.project_id
  cluster_name     = data.terraform_remote_state.gke.outputs.gke1_name
  location         = data.terraform_remote_state.gke.outputs.gke1_location
  cluster_endpoint = data.terraform_remote_state.gke.outputs.gke1_endpoint
  ssh_auth_key     = file("csr-key")
  create_ssh_key   = false
  sync_repo        = data.terraform_remote_state.repos.outputs.acm_repo_ssh_url
  #sync_repo        = "ssh://${var.user}@source.developers.google.com:2022/p/${data.terraform_remote_state.vpc.outputs.project_id}/r/${google_sourcerepo_repository.acm_repo.name}"
}
```

I commented out the original `sync_repo` and added the new one. Checked cluster status after apply and it still points to the old one.

tf plan seems to show the correct value for the new `sync_repo`.

```
  # module.gke2_acm.module.acm_operator.local_file.operator_cr will be created
  + resource "local_file" "operator_cr" {
      + content              = <<~EOT
            apiVersion: configmanagement.gke.io/v1
            kind: ConfigManagement
            metadata:
              name: config-management
            spec:
              # clusterName is required and must be unique among all managed clusters
              clusterName: gke2-r1b-prod
              policyController:
                enabled: true
                templateLibraryInstalled: true
                logDeniesEnabled: false
              git:
                syncRepo: git@gitlab.endpoints.qwiklabs-gcp-ml-76b0c8a85f9e.cloud.goog:platform-admins/anthos-config-management.git
                secretType: ssh
```

Applies without issues.

Logs from the `git-importer`, as well as the `configmanagement` resource in the cluster, shows the old `sync_repo`.

Logs:
```
I0902 01:51:26.573062      12 main.go:574]  "level"=0 "msg"="cloning repo"  "origin"="ssh://student-00-2de3e9024482@qwiklabs.net@source.developers.google.com:2022/p/qwiklabs-gcp-ml-76b0c8a85f9e/r/acm" "path"="/repo/root"
```

Configmanagement resource:
```
kubectl describe configmanagement
Name:         config-management
Namespace:
Labels:       <none>
Annotations:  API Version:  configmanagement.gke.io/v1
Kind:         ConfigManagement
Metadata:
  Creation Timestamp:  2020-09-02T00:31:32Z
  Finalizers:
    operator.configmanagement.gke.io
    policycontroller.configmanagement.gke.io
    policycontroller.configmanagement.gke.io/library
  Generation:        3
  Resource Version:  15604
  Self Link:         /apis/configmanagement.gke.io/v1/configmanagements/config-management
  UID:               8c78ef3f-1d54-48a1-8804-380c6902d4cb
Spec:
  Application Controller:          <nil>
  Config Sync Disable FS Watcher:  false
  Config Sync Log Level:           0
  Config Sync Pod Resources:
  Cluster Name:  gke1-r1a-prod
  Git:
    Proxy:
    Secret Type:  ssh
    Sync Repo:    ssh://student-00-2de3e9024482@qwiklabs.net@source.developers.google.com:2022/p/qwiklabs-gcp-ml-76b0c8a85f9e/r/acm
```
